### ISSUE TITLE
error running Jasmine on server deployment bug

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/forest#133]
(Assigning to Zach because you have full server access)

Commit hash (the first line of output from `git show`):
2402c6f73d3e562dc346e39ba0408cd9f460785
(it may be time for a new target commit hash, this is from the `nh/sycamore_integration` branch on beiwe backend, its a couple months old but is the most up to date target commit I've been told to use.)

**Describe the bug**
These occur when running under the forest runtime, data is already present etc.
I am posting two bugs here, let me know when testing them to confirm the commit hash hasn't changed. (should be in summary tho)

**To reproduce**
run jasmine on full date range for these two users on the "debugging study that generates lots of data" study across the whole date range, which is 2018-4-16 to 2022-9-9 (currently, anyway).
a user with bug 1: `jyjneczo`
a user with bug 2: `qwfua4on`
You can see the tasks run at https://staging.beiwe.org/studies/3/forest/tasks
You can dispatch new tasks here: https://staging.beiwe.org/studies/3/forest/tasks/create  (this study has a lot of tests run on it, so it can be a mess)

the default parameters (example)
```
{'all_bv_set': None,
 'all_memory_dict': None,
 'frequency': 'daily',
 'output_folder': '/tmp/forest/3d67042d-b119-4810-84a8-c3b39261d634/jasmine/output',
 'save_traj': False,
 'study_folder': '/tmp/forest/3d67042d-b119-4810-84a8-c3b39261d634/jasmine/data',
 'time_end': [2022, 9, 10, 0, 0, 0, 0],
 'time_start': [2018, 4, 16, 0, 0, 0, 0],
 'tz_str': 'America/New_York'}
```

**Observed behavior**
relevant sections of stack traces excluding Beiwe Backend server stuff, bug 1:
```
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 1002, in gps_stats_main
    mobmat1 = GPS2MobMat(
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/data2mobmat.py", line 276, in GPS2MobMat
    avgmat = collapse_data(data, itrvl, accuracylim)
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/data2mobmat.py", line 126, in collapse_data
    t_start = sorted(np.array(data.timestamp))[0]/1000
IndexError: list index out of range
```

bug 2:
```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 1000, in gps_stats_main
    parameters.w = np.mean(data.accuracy)
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'accuracy'
```

**Comment by biblicabeebli** [comment]
Another error I just didn't see, participant "uqecgbsf" on the same debugging study.

```
  File "forest/jasmine/traj2stats.py", line 1006, in gps_stats_main
    mobmat2 = InferMobMat(mobmat1, parameters.itrvl, parameters.r)
  File "forest/jasmine/data2mobmat.py", line 413, in InferMobMat
    mobmat = np.vstack((mobmat,new_pauses))
  File "<__array_function__ internals>", line 180, in vstack
    return implement_array_function(
  File "numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
    return implement_array_function(

```

**Comment by clementzach** [comment]
Thanks, @biblicabeebli 

Just to clarify, I'm running these on my local machine using that same commit, then verifying that the error still exists on my local, correct?

Would you want me to create bug reports/work on fixing the actual code?

**Comment by biblicabeebli** [comment]
This tracking issue is sufficient, just let me know when a stable target commit exists, and let me know if its best to try it out on staging first or if it should go out to everyone.

(my internet died for an hour, I'm slightly crossing email alerts from my phone in my head here, this work is slightly connected to https://github.com/onnela-lab/beiwe-backend/pull/288 in that it all resulted from the same batch of work on my end.)

**Comment by biblicabeebli** [comment]
There have been some new errors from running data analyses on staging last ~week, commit should be 2402c6f73d3e562dc346e39ba0408cd9f4607857.

Including sentry links for @clementzach if he needs them

https://sentry.io/organizations/onnela-lab/issues/3709586875/?project=143573&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
```
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
  File "services/celery_forest.py", line 152, in run_forest_task
    run_forest(task)
  File "services/celery_forest.py", line 189, in run_forest
    TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
  File "forest/jasmine/traj2stats.py", line 1018, in gps_stats_main
    imp_table = ImputeGPS(mobmat2, bv_set, parameters.method,
  File "forest/jasmine/mobmat2traj.py", line 212, in ImputeGPS
    mis_t0 = mis_table[i,2]; mis_t1 = mis_table[i,5]
```

https://sentry.io/organizations/onnela-lab/issues/3709855718/?project=143573&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
```
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
  File "services/celery_forest.py", line 152, in run_forest_task
    run_forest(task)
  File "services/celery_forest.py", line 189, in run_forest
    TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
  File "forest/jasmine/traj2stats.py", line 1006, in gps_stats_main
    mobmat2 = InferMobMat(mobmat1, parameters.itrvl, parameters.r)
  File "forest/jasmine/data2mobmat.py", line 309, in InferMobMat
    code = mobmat[:,0]
```

https://sentry.io/organizations/onnela-lab/issues/3709417815/?project=143573&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
```
ValueError: max() arg is an empty sequence
  File "services/celery_forest.py", line 152, in run_forest_task
    run_forest(task)
  File "services/celery_forest.py", line 189, in run_forest
    TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
  File "forest/jasmine/traj2stats.py", line 1018, in gps_stats_main
    imp_table = ImputeGPS(mobmat2, bv_set, parameters.method,
  File "forest/jasmine/mobmat2traj.py", line 204, in ImputeGPS
    home_x,home_y = locate_home(MobMat,tz_str)
  File "forest/jasmine/mobmat2traj.py", line 56, in locate_home
    home_index = num_xy.index(max(num_xy))
```


https://sentry.io/organizations/onnela-lab/issues/3709736730/?project=143573&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
```
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 8 and the array at index 1 has size 0
  File "services/celery_forest.py", line 152, in run_forest_task
    run_forest(task)
  File "services/celery_forest.py", line 189, in run_forest
    TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
  File "forest/jasmine/traj2stats.py", line 1006, in gps_stats_main
    mobmat2 = InferMobMat(mobmat1, parameters.itrvl, parameters.r)
  File "forest/jasmine/data2mobmat.py", line 413, in InferMobMat
    mobmat = np.vstack((mobmat,new_pauses))
  File "<__array_function__ internals>", line 180, in vstack
    return implement_array_function(
  File "numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
    return implement_array_function(
```

**Comment by clementzach** [comment]
Sorry it's taken me so long to get to these errors...

I'm prioritizing my thesis for now, but I'll get to this the end of this week or next week

**Comment by biblicabeebli** [comment]
And another one

```
ValueError: a must be greater than 0 unless no samples are taken
  File "services/celery_forest.py", line 152, in run_forest_task
    run_forest(task)
  File "services/celery_forest.py", line 189, in run_forest
    TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
  File "forest/jasmine/traj2stats.py", line 1018, in gps_stats_main
    imp_table = ImputeGPS(mobmat2, bv_set, parameters.method,
  File "forest/jasmine/mobmat2traj.py", line 339, in ImputeGPS
    flight_index = np.random.choice(flight_table.shape[0], p=normalize_w)
  File "mtrand.pyx", line 909, in numpy.random.mtrand.RandomState.choice
```

**Comment by biblicabeebli** [comment]
@clementzach Prioritize that thesis!  These can be addressed and investigated later, these all seem to be edge cases involving empty data in unexpected locations.

**Comment by biblicabeebli** [comment]
The forest task runner on the beiwe-taskrunner branch can now run an up to date version of all 4 supported forest trees, including jasmine.

Rerunning these forest tasks to see if they work now.

**Comment by biblicabeebli** [comment]
ok @clementzach this issue is now officially resurrected - now with colorized syntax highlighting!

New run that actually runs jasmine:
uhhh we need to add some kind of unique identifier column, its this one:
`2023-11-16 20:16 (UTC) 	jyjneczo 	Jasmine 	2018-04-16 	2023-11-08 	error `

```python
Traceback (most recent call last):
  File "/home/ubuntu/beiwe-backend/services/celery_forest.py", line 165, in run_forest_task
    run_forest(task)
  File "/home/ubuntu/beiwe-backend/services/celery_forest.py", line 202, in run_forest
    TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 1674, in gps_stats_main
    mobmat1 = gps_to_mobmat(
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/data2mobmat.py", line 588, in gps_to_mobmat
    avgmat = collapse_data(raw_gps_data, interval, accuracy_limit)
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/data2mobmat.py", line 184, in collapse_data
    t_start = sorted(np.array(data.timestamp))[0] / 1000
IndexError: list index out of range
```

There is not currently a rerun button - um, sorry about that

forest version is my beiwe-taskrunner branch commit 810ef6c1f2779c46be402819fd807402b6769387

IIIII also need to add the commit it was run with to the task view.

**Comment by biblicabeebli** [comment]
Good news! Bug 2 (qwfua4on) appears to be resolved, that task ran to conclusion.

**Comment by clementzach** [comment]
@hydawo before I start working on this, could you confirm that I'm the right person to resolve this issue? I'm happy to, but don't want to bill you guys unnecessarily if this would fall better into another person's scope

**Comment by biblicabeebli** [comment]
This bug is long-fixed, right?

**Comment by biblicabeebli** [comment]
@GeorgeEfstathiadis can you comment on whether this issue is resolved?

**Comment by GeorgeEfstathiadis** [comment]
> ok @clementzach this issue is now officially resurrected - now with colorized syntax highlighting!
> 
> New run that actually runs jasmine: uhhh we need to add some kind of unique identifier column, its this one: `2023-11-16 20:16 (UTC) jyjneczo Jasmine 2018-04-16 2023-11-08 error `
> 
> ```python
> Traceback (most recent call last):
>   File "/home/ubuntu/beiwe-backend/services/celery_forest.py", line 165, in run_forest_task
>     run_forest(task)
>   File "/home/ubuntu/beiwe-backend/services/celery_forest.py", line 202, in run_forest
>     TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
>   File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 1674, in gps_stats_main
>     mobmat1 = gps_to_mobmat(
>   File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/data2mobmat.py", line 588, in gps_to_mobmat
>     avgmat = collapse_data(raw_gps_data, interval, accuracy_limit)
>   File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/data2mobmat.py", line 184, in collapse_data
>     t_start = sorted(np.array(data.timestamp))[0] / 1000
> IndexError: list index out of range
> ```
> 
> There is not currently a rerun button - um, sorry about that
> 
> forest version is my beiwe-taskrunner branch commit [810ef6c](https://github.com/onnela-lab/forest/commit/810ef6c1f2779c46be402819fd807402b6769387)
> 
> IIIII also need to add the commit it was run with to the task view.

You mean this bug right? This is resolved yes

**Comment by biblicabeebli** [comment]
Great
