### ISSUE TITLE
ValueError: all the input array dimensions... running Jasmine on server.

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/forest#231]
info is on https://studies.beiwe.org/studies/934/forest/tasks
task id is e899fe60-6a82-4f01-ab3a-950a804b24d1 
commit hash should be fcc49a74057f98b1b26079a0257b3e9d7c27a98f - its a commit on my beiwe-taskrunner branch.

```python
Traceback (most recent call last):
  File "/home/ubuntu/beiwe-backend/services/celery_forest.py", line 165, in run_forest_task
    run_forest(task)
  File "/home/ubuntu/beiwe-backend/services/celery_forest.py", line 216, in run_forest
    TREE_TO_FOREST_FUNCTION[forest_task.forest_tree](**params_dict)
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 1678, in gps_stats_main
    mobmat2 = infer_mobmat(mobmat1, parameters.itrvl, params_r)
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/forest/jasmine/data2mobmat.py", line 1003, in infer_mobmat
    mobmat = np.vstack((mobmat, new_pauses_array))
  File "<__array_function__ internals>", line 180, in vstack
  File "/home/ubuntu/.pyenv/versions/beiwe/lib/python3.8/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 8 and the array at index 1 has size 0
```

**Comment by biblicabeebli** [comment]
Sentry link it case I need it later.
https://onnela-lab.sentry.io/issues/4690601355/?project=143573&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=4
