### ISSUE TITLE
Wait time is too long for Openrouteservice errors

### ISSUE THREAD

**Issue by hackdna** [onnela-lab/forest#72]
### To reproduce
Run the following command with an invalid API key:
```
sample_gps_data = sim_gps_data(n_persons, location, start_date, end_date, cycle, percentage, api_key, personal_attributes)
```

### Observed results
It took about 90 seconds to get this error:
```
Loading Attributes...
Gathering Addresses...
Starting to generate trajectories...
Traceback (most recent call last):
  File "/Users/ils475/code/forest/forest/bonsai/simulate_gps_data.py", line 106, in get_path
    routes = client.directions(
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/openrouteservice/client.py", line 299, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/openrouteservice/directions.py", line 281, in directions
    return client.request("/v2/directions/" + profile + '/' + format, {}, post_json=params, dry_run=dry_run)
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/openrouteservice/client.py", line 204, in request
    result = self._get_body(response)
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/openrouteservice/client.py", line 242, in _get_body
    raise exceptions.ApiError(
openrouteservice.exceptions.ApiError: 403 ({'error': 'Daily quota reached or API key unauthorized'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ils475/code/forest/forest/bonsai/simulate_gps_data.py", line 1382, in sim_gps_data
    all_traj, all_times, all_distances = gen_all_traj(
  File "/Users/ils475/code/forest/forest/bonsai/simulate_gps_data.py", line 959, in gen_all_traj
    go_path, transport = person.calculate_trip(
  File "/Users/ils475/code/forest/forest/bonsai/simulate_gps_data.py", line 609, in calculate_trip
    path, _ = get_path(
  File "/Users/ils475/code/forest/forest/bonsai/simulate_gps_data.py", line 110, in get_path
    raise RuntimeError(
RuntimeError: Openrouteservice did not return proper trajectories.
```

### Expected results
These errors should not take that long to receive.

I think the best way to solve this is to remove the retry logic from `calculate_trip()` and simply let Forest users handle retries as necessary: https://github.com/onnela-lab/forest/blob/fc6e90414b2aea75fe8e93e40bcad55df914687c/forest/bonsai/simulate_gps_data.py#L606

**Comment by GeorgeEfstathiadis** [comment]
I don't think removing the retry logic will work. Since the simulation goes kind of iteratively, day by day, then the Openrouteservice api is called a lot of times very fast and that throws an error a RuntimeError about calling on the API too many times that quickly. Having the retry logic there makes it so if such an error is raised, you wait for some time and then it continues working. Without it the algorithm will always throw an error so it will never return the trajectories. I think maybe I can find a way to check if api key is valid in the beginning of the simulations and leave the retry logic in. What do you think?

**Comment by hackdna** [comment]
OK, I see that there is a 40 requests per minute limit for the directions API. So, adding a 1.5 second delay between calls should eliminate the need for retries (and avoid overloading the Openrouteservice API by accident). Additionally, you can either check the X-RateLimit- Headers for the remaining quota or check the response code for the specific error code (429?) related to the request limits.

Reference:
https://openrouteservice.org/plans/
https://ask.openrouteservice.org/t/what-is-the-logic-behind-x-ratelimit-reset/3040
https://github.com/GIScience/openrouteservice-py/blob/master/openrouteservice/exceptions.py
