### ISSUE TITLE
Slow summary stats calculation in Jasmine

### ISSUE THREAD

**Issue by hackdna** [onnela-lab/forest#78]
Running Jasmine on a single study participant using the latest code in main (8f1a42a):
```
>>> tz_str = "America/New_York"
>>> option = "daily"
>>> save_traj = False
>>> time_start = None
>>> time_end = None
>>> parameters = None
>>> all_memory_dict = None
>>> all_BV_set= None
>>> gps_stats_main(path_to_gps_data, path_to_gps_summary, tz_str, option, save_traj, time_start, time_end, beiwe_id, parameters, all_memory_dict, all_BV_set)
```
The run time is just over one minute.

Running Jasmine on the same single study participant using the latest code in develop (7db0f25):
```
>>> tz_str = "Etc/GMT-1"
>>> frequency = Frequency.DAILY
>>> save_traj = False
>>> parameters = None
>>> places_of_interest = ['cafe', 'bar', 'hospital']
>>> save_log = True
>>> threshold = 15
>>> gps_stats_main(path_to_gps_data, path_to_gps_summary, tz_str, frequency, save_traj, parameters, places_of_interest, save_log, threshold, participant_ids=participant_ids)
```
The run time is over one hour (more than 60x slower).

**Comment by hackdna** [comment]
I actually had to interrupt the second run because it was taking way too long but here's the output:
```
Calculating the daily summary stats...
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ils475/code/forest/forest/jasmine/traj2stats.py", line 1068, in gps_stats_main
    summary_stats, logs = gps_summaries(
  File "/Users/ils475/code/forest/forest/jasmine/traj2stats.py", line 483, in gps_summaries
    location_circle = transform_point_to_circle(
  File "/Users/ils475/code/forest/forest/jasmine/traj2stats.py", line 94, in transform_point_to_circle
    wgs84_to_aeqd = Transformer.from_crs(
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/pyproj/transformer.py", line 565, in from_crs
    return Transformer(
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/pyproj/transformer.py", line 310, in __init__
    self._local.transformer = transformer_maker()
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/pyproj/transformer.py", line 97, in __call__
    return _Transformer.from_crs(
  File "pyproj/_transformer.pyx", line 1003, in pyproj._transformer._Transformer.from_crs
  File "pyproj/_transformer.pyx", line 1073, in pyproj._transformer._Transformer._init_from_crs
  File "pyproj/_transformer.pyx", line 813, in pyproj._transformer._Transformer._initialize_from_projobj
  File "/Users/ils475/.pyenv/versions/forest/lib/python3.8/site-packages/pyproj/exceptions.py", line 19, in clear
    @staticmethod
KeyboardInterrupt
```
This might indicate that `transform_point_to_circle()` is in the hot path.

**Comment by GeorgeEfstathiadis** [comment]
For the first run you did, 60 minutes seems a lot indeed, but we expect it to take a lot more time with the new summary statistics to calculate. Can you try the same experiment with `places_of_interest = None` and `save_log = False`, since that is when both versions of the code calculate the same thing thus should take approximately the same time to run.

**Comment by GeorgeEfstathiadis** [comment]
For the second run,

> This might indicate that `transform_point_to_circle()` is in the hot path.

What do you mean, you think this is the function that makes it slow?

**Comment by hackdna** [comment]
Yes, it looks like `transform_point_to_circle()` is the one making it slow but it's not absolutely certain because it's just one data point.

I will try again with the parameter values you have suggested and will report back with the results. I'll also email you the data I have used so that you could reproduce the issue locally.

**Comment by hackdna** [comment]
Running with `places_of_interest = None` and `save_log = False` took just over a minute.
