### ISSUE TITLE
Sycamore agg_data can be NoneType

### ISSUE THREAD

**Issue by clementzach** [onnela-lab/forest#81]
There are timers when agg_data is None. This needs to not happen. 

Traceback:

Traceback (most recent call last):
    sycamore_main.survey_stats_main(output_dir = output_folder, study_dir = download_folder, beiwe_ids = [])
  File "/Volumes/SanDisk/opt/anaconda3/envs/python_3_8/lib/python3.8/site-packages/forest/sycamore/sycamore_main.py", line 30, in survey_stats_main
    agg_data = aggregate_surveys_no_config(study_dir, study_tz)
  File "/Volumes/SanDisk/opt/anaconda3/envs/python_3_8/lib/python3.8/site-packages/forest/sycamore/functions.py", line 328, in aggregate_surveys_no_config
    agg_data['submit_line'] = agg_data.apply(lambda row: 1 if row['event'] in ['User hit submit', 'submitted'] else 0,
AttributeError: 'NoneType' object has no attribute 'apply'

**Comment by clementzach** [comment]
This is fixed in the fix_survey_timings branch/pull request
