### ISSUE TITLE
Sycamore merging on different cols issue

### ISSUE THREAD

**Issue by clementzach** [onnela-lab/forest#84]
Here is the error trace:

And Debbie has sent me the reproducible example in a file, but I won't post it here.

Downloading data for gedbuk34
Traceback (most recent call last):
  File "/Users/debbiehuang/Desktop/Van_Meter_Sycamore_Code/fulford_surveys/run_sycamore.py", line 31, in <module>
    main()
  File "/Users/debbiehuang/Desktop/Van_Meter_Sycamore_Code/fulford_surveys/run_sycamore.py", line 23, in main
    survey_stats_main(args.output_dir, args.study_dir, args.beiwe_ids,
  File "/Users/debbiehuang/Desktop/Van_Meter_Sycamore_Code/fulford_surveys/env/lib/python3.10/site-packages/forest/sy
camore/sycamore_main.py", line 40, in survey_stats_main
    ss_detail, ss_summary = survey_submits(study_dir, config_path, time_start, time_end, beiwe_ids, agg_data,
 
  File "/Users/debbiehuang/Desktop/Van_Meter_Sycamore_Code/fulford_surveys/env/lib/python3.10/site-packages/forest/sy
camore/survey_config.py", line 182, in survey_submits
    submit_lines3 = pd.merge(submit_lines2, submit_lines[merge_cols + ['Local time']], how='left', left_on=merge_cols
,
  File "/Users/debbiehuang/Desktop/Van_Meter_Sycamore_Code/fulford_surveys/env/lib/python3.10/site-packages/pandas/co
re/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/Users/debbiehuang/Desktop/Van_Meter_Sycamore_Code/fulford_surveys/env/lib/python3.10/site-packages/pandas/co
re/reshape/merge.py", line 704, in __init__
    self._maybe_coerce_merge_keys()
  File "/Users/debbiehuang/Desktop/Van_Meter_Sycamore_Code/fulford_surveys/env/lib/python3.10/site-packages/pandas/co
re/reshape/merge.py", line 1261, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on datetime64[ns] and object columns. If you wish to proceed you should use pd.concat

**Comment by clementzach** [comment]
This is fixed in the fix_survey_timings branch.
