### ISSUE TITLE
Forest package fails to install correctly

### ISSUE THREAD

**Issue by hackdna** [onnela-lab/forest#86]
To reproduce:
Don't clone the repo then just install the package
```
pip install git+https://github.com/onnela-lab/forest
python -c "from forest.jasmine.traj2stats import gps_stats_main"
```

Observed results:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ils475/.pyenv/versions/forest-test/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 21, in <module>
    from forest.bonsai.simulate_gps_data import bounding_box
  File "/Users/ils475/.pyenv/versions/forest-test/lib/python3.8/site-packages/forest/bonsai/simulate_gps_data.py", line 21, in <module>
    from forest.constants import (ORS_API_BASE_URL, ORS_API_CALLS_PER_MINUTE,
ModuleNotFoundError: No module named 'forest.constants'
```

Expected results:
No error

Originally reported in https://github.com/onnela-lab/forest/pull/80#issuecomment-1043290393 and https://github.com/onnela-lab/forest/pull/85#issuecomment-1043309803

**Comment by hackdna** [comment]
Solved in [fb8861c](https://github.com/onnela-lab/forest/commit/fb8861c6bc5a3f268cf357612913516d5e705d38)
